### ISSUE TITLE
Add favorites

### ISSUE THREAD

**Issue by peterdickx** [jimbob4000/RetroFlow-Launcher#46]
Hi, i have created a fork of retroflow in which i have added the ability to add favorites (and also added neo geo pocket color). I still have a few issues, i was wondering i you woulf like to colaborate on this? https://github.com/peterdickx/RetroFlow-Launcher/tree/Favorites

**Comment by jimbob4000** [comment]
Hi Peter,

Thanks for the constribution.
Sorry for the slow response, I'm struggling to find the time and will to move forward with the project.

I've had a quick look at the code and started adding to mine from the base upwards based around the approach below.

I think it may work best if the user goes to the game info screen then presses triangle to mark the game as a favourite.
This allows people to still change view with circle.

Marking as a fav on the info screen also allows time for the favourite, all, and current system tables to be refreshed and cached.

The favourite icon could perhaps be shown to the left of the clock instead of on the boxes, (top right on the info view).

I'm happy for you to progress and release forked versions provided credit is still given to VitaHex for the original version.

There's some great ideas in the issues and requests for this fork, I'm just struggling to move forward with it.
To be honest I'm thinking anout archiving the fork, but at the moment there's some good ideas being gathered here.

**Comment by jimbob4000** [comment]
I've made some progress on this using the approach I mentioned above. 

It took a lot more code than I thought to update the lists quickly without reloading, but seems to be working okay. 

Thanks for the pull request it gave me a bit of a head start. 

Should be out in the next release. 
(No date set, will bundle it with some other stuff).

**Comment by peterdickx** [comment]
Hi, thanks! the merge request was not really needed, i just wanted an easy way to share my changes to your code.
